// CATALOG (Movebank) — enumerate the publicly-listed Movebank studies (no auth).
//
// The public study-list endpoint returns only id / name / sensor / license-terms
// flag. The per-study LICENSE TYPE (needed to gate CC0/CC-BY) and metadata return
// 401 without a Movebank account. So we CANNOT add these to the commercial-safe
// `datasets` index yet — we write a PENDING list and a RUN_WHEN_READY note. Once
// MOVEBANK_USER/PASS are set, a follow-up can read license_type + taxa and ingest
// the CC0/CC-BY ones via lib/sources/movebank.ts (handshake already implemented).
//
// Usage: pnpm catalog-movebank
import { writeFileSync } from "node:fs";

const URL_STUDIES = "https://www.movebank.org/movebank/service/public/json?entity_type=study";

interface PublicStudy { id: number; name: string; sensor_type_ids?: string; suspend_license_terms?: boolean }

function taxonFromName(name: string): string {
  const t = name.toLowerCase();
  if (/gull|stork|spoonbill|curlew|harrier|kestrel|eagle|goose|geese|duck|tern|oystercatcher|godwit|crane|owl|bird|petrel|albatross|gannet|swan|heron|falcon|vulture|eider|scoter|frugivore/.test(t)) return "bird";
  if (/seal|whale|dolphin|cetacean|\bbat\b|deer|\bfox\b|wolf|bear|elephant|lion|mammal|rodent|hare|boar|badger|otter|lynx|baboon|primate/.test(t)) return "mammal";
  if (/salmon|sturgeon|\bcod\b|shark|\bfish|tuna|eel/.test(t)) return "fish";
  if (/turtle|tortoise|snake|lizard|reptile|crocodile/.test(t)) return "reptile";
  return "other/unknown";
}

// Movebank rate-limits/intermittently returns a non-JSON terms message; retry.
async function fetchStudies(tries = 5): Promise<PublicStudy[]> {
  for (let attempt = 0; attempt < tries; attempt++) {
    try {
      const res = await fetch(URL_STUDIES, {
        headers: { "User-Agent": "migration-stories/0.1" },
        signal: AbortSignal.timeout(90000),
      });
      const text = await res.text();
      if (text.trimStart().startsWith("[")) return JSON.parse(text) as PublicStudy[];
      process.stderr.write(`  (non-JSON response, retrying: "${text.slice(0, 40)}…")\n`);
    } catch (e) {
      process.stderr.write(`  (fetch error, retrying)\n`);
    }
    await new Promise((r) => setTimeout(r, 3000 * (attempt + 1)));
  }
  throw new Error("Movebank: could not fetch study list after retries");
}

async function main() {
  console.log("\n=== Movebank public study list (no auth) ===\n");
  const studies = await fetchStudies();
  console.log(`Public studies returned: ${studies.length}`);

  const gps = studies.filter((s) => /gps/i.test(s.sensor_type_ids ?? ""));
  const byTaxon = new Map<string, number>();
  for (const s of studies) byTaxon.set(taxonFromName(s.name), (byTaxon.get(taxonFromName(s.name)) ?? 0) + 1);

  const rows = [...studies]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((s) => `| ${s.id} | ${s.name.slice(0, 70).replace(/\|/g, "/")} | ${(s.sensor_type_ids ?? "").slice(0, 20)} | ${taxonFromName(s.name)} |`);

  const md = `# Movebank — public studies (PENDING license verification)

Generated by \`pnpm catalog-movebank\` from Movebank's public study-list endpoint
(no auth). **These are NOT yet in the commercial-safe \`datasets\` index**, because
the per-study \`license_type\` is only readable with a Movebank account (the study
metadata endpoint returns HTTP 401 anonymously). We must confirm CC0 / CC-BY
before surfacing any of these.

- **${studies.length}** public studies listed (license terms pre-suspended → downloadable).
- **${gps.length}** report a GPS sensor.

## By taxon (heuristic, from study name)

| Taxon | Studies |
| --- | ---: |
${[...byTaxon.entries()].sort((a, b) => b[1] - a[1]).map(([k, v]) => `| ${k} | ${v} |`).join("\n")}

## To unlock

Set \`MOVEBANK_USER\` / \`MOVEBANK_PASS\` in \`.env\`, then a follow-up script can read
each study's \`license_type\` + taxa, gate to CC0/CC-BY, and ingest events via
\`lib/sources/movebank.ts\` (the license handshake is already implemented + tested).

## All public studies (id · name · sensor · taxon guess)

| Study ID | Name | Sensor | Taxon |
| --- | --- | --- | --- |
${rows.join("\n")}
`;

  writeFileSync(new URL("../MOVEBANK_PENDING.md", import.meta.url), md);
  console.log(`✓ Wrote MOVEBANK_PENDING.md (${studies.length} studies, ${gps.length} GPS)`);
  process.exit(0);
}

main().catch((e) => { console.error(e); process.exit(1); });
