// Turn the generated landing.html into React-mountable assets, so the Next app
// and the standalone artifact stay pixel-identical from ONE source (no drift):
//   • components/hero.generated.ts — the exact CSS, body markup, and hero logic
//   • public/data/web.json         — the heavy payload, served static & cached
// The hero logic is wrapped as window.__heroRun(D); the component fetches the
// JSON and calls it. Re-run this whenever build-landing.ts runs.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";

const R = (p: string) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const html = readFileSync(R("landing.html"), "utf8");

const css = html.match(/<style>([\s\S]*?)<\/style>/)?.[1];
const scriptFull = html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
if (!css || !scriptFull) throw new Error("could not extract <style>/<script> from landing.html");

// body markup = everything between </style> and <script>
let body = html.slice(html.indexOf("</style>") + "</style>".length, html.indexOf("<script>")).trim();

// landing.html links the findings report at its standalone artifact URL, which is
// correct for the standalone artifact. On the site the report lives at /findings,
// so point there instead: an off-site link from our own domain reads as broken and
// sends readers away. One source, two correct destinations.
const REPORT_ARTIFACT = /https:\/\/claude\.ai\/code\/artifact\/30239285-1e14-495d-b4b2-426f135d36ed/g;
if (!REPORT_ARTIFACT.test(body)) console.warn("⚠ report artifact link not found in landing.html — check the CTA href");
body = body.replace(REPORT_ARTIFACT, "/findings");

// the script's first statement is `const D = {…};` — lift that object out to a
// static JSON file and turn the rest into a function of D.
const script = scriptFull.trimStart();
const nl = script.indexOf("\n");
const firstLine = script.slice(0, nl).trim();
const rest = script.slice(nl + 1);
const m = firstLine.match(/^const D = (.*);$/);
if (!m) throw new Error("expected first script line to be `const D = {…};`, got: " + firstLine.slice(0, 60));
const dJson = m[1];
JSON.parse(dJson); // validate it's real JSON

// runnable: defines a global the component calls once the payload has loaded
const runnable = `(function(){window.__heroRun=function(D){\n${rest}\n};})();`;

mkdirSync(R("public/data"), { recursive: true });
writeFileSync(R("public/data/web.json"), dJson);

const out =
  `// AUTO-GENERATED by scripts/gen-hero-component.ts from landing.html — do not edit.\n` +
  `/* eslint-disable */\n` +
  `export const HERO_CSS = ${JSON.stringify(css)};\n` +
  `export const HERO_BODY = ${JSON.stringify(body)};\n` +
  `export const HERO_SCRIPT = ${JSON.stringify(runnable)};\n`;
writeFileSync(R("components/hero.generated.ts"), out);

console.log(`✓ components/hero.generated.ts (${(out.length / 1024).toFixed(0)} KB)`);
console.log(`✓ public/data/web.json (${(dJson.length / 1024).toFixed(0)} KB)`);
