// Turn the generated report.html into React-mountable assets, the same trick as
// scripts/gen-hero-component.ts: ONE source (report.html) serves both the
// standalone artifact and the site's /findings page, so they can never drift.
//
// The standalone report is light by default with a dark override (it lives in a
// surface that has a theme toggle). The site is committed to a single dark world,
// so the generated copy appends a palette lock rather than forking the stylesheet.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const R = (p: string) => fileURLToPath(new URL(`../${p}`, import.meta.url));
const html = readFileSync(R("report.html"), "utf8");

const css = html.match(/<style>([\s\S]*?)<\/style>/)?.[1];
const script = html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
if (!css || !script) throw new Error("could not extract <style>/<script> from report.html");

const body = html.slice(html.indexOf("</style>") + "</style>".length, html.indexOf("<script>")).trim();

// Lock the report's variables to the site's dark palette (globals.css). Names differ
// between the two stylesheets, so this maps rather than duplicates.
const DARK_LOCK = `
/* --- site override: this page lives in the dark instrument, not a themed surface --- */
:root, :root[data-theme="dark"], :root[data-theme="light"]{
  --bg:#03090c; --surface:#06141a; --text:#d8e8eb; --muted:#6e8c94; --rule:#123039;
  --cold:#58d2e6; --warm:#ffb24d; --unwatched:#12343e; --shadow:rgba(0,0,0,.45);
}
`;

const runnable = `(function(){window.__reportRun=function(){\n${script}\n};})();`;

const out =
  `// AUTO-GENERATED by scripts/gen-report-component.ts from report.html — do not edit.\n` +
  `/* eslint-disable */\n` +
  `export const REPORT_CSS = ${JSON.stringify(css + DARK_LOCK)};\n` +
  `export const REPORT_BODY = ${JSON.stringify(body)};\n` +
  `export const REPORT_SCRIPT = ${JSON.stringify(runnable)};\n`;
writeFileSync(R("components/report.generated.ts"), out);

console.log(`✓ components/report.generated.ts (${(out.length / 1024).toFixed(0)} KB)`);
